package Eken.Shops.response;

public class YapilacakAndYapilan {
    // en son Category ile urunler getirildi
    //Jignore iptal edildi
    //AllProduct Jignoresiz gelebiliyor, bisey yapmadik, gelebilir, cunku calssdaki diger bagliliklarda geliyor,bu ilerde is yuju olabilir

    //  UI DA KART GORUNUMLU URUNLER ICIN AYRI SORGU VE GET ISLEMI YAPILABILIR, TUM URUN BILGILERIN GITMESINE VEYA TUM URUNLERIN GITMESINE
    // GEREK YOK == CART ICIN AYRI BIR SORGUYU SIMDILIK YAPMADIM. EGER YUKLEMEDE ZORLAMA OLURSA KISA KART GORUNUMUNE GECILEBILIR
    //   => PRODUCT OZELLIKLERININ TAMAMININ GONDERILMESI, URUN DETAYLI INCELENMEK ICIN TIKLANIRSA ZATEN GELEN BILGILER ICERISINDE DE OLACAGI ICIN ZAMAN KAYBI YASANMAMIS OLUR
    //  =>SADECE URUN ACIKLAMALARI ISTENMESI YETERLIOLACAKTIR


    // ISTENIRSE VE TIKLANIRSA URUN YORUMLARI CAGIRILABILIR. TUM YORUMLARIN GELMESI SORUN OLABILIR. ZAMAN ACISINDAN... ILK 10 YORUM ACILIR DAHA SONRA DA 10 10 ISTENEBILIR. VEYA 20
    //    => userkontrolde urunyorumu getir olusturalim, Product tablosunda
    //    =>yorum ekle menusu olusturalim, user control ya da transaccontroller da

    // NOT : YAPILAN YORUMLAR ICIN IKINCI BIR TABLO OLUSTURULABILIR. BU TABLOYA ILK OLARAK ONAYSIZ YORUMLAR DAHIL EDILIR, ONAY SONRASI IKINCI ASIL TABLOYA URUNLER ALINABILIR.
    // yeni tablo olusturulacak,
    // ONAYLANAN YORUM TEKRAR DAN GOZDEN GECIRILIR VE KAYDEDILIR ISE TEKRARDAN YORUM SAYISI VE YILDIZ SAYISI ARTIYOR, BUNUNICIN IKINCI BIR TABO ONEMLI
    // YA DA YILDIZ ORTALAMASI VE YORUM SAYISI ICIN AYRICA BIR KOD YAZILIR VE TUM URUNLERIN YORUM VE ILDIZI TOPLUCA HESAPLANI, BU DA IS YUKU OLUSTURUR. SITEYI DURDURABILIR.
    //      => admin kontrolde yorumlari getir, tek yorum getir, yorumlari onayla, onaylanmayanlari onayszi yorumlar tablosuna ekleyelim,
    // ONAYLANAN YORUM SONRASI YORUM SAYISI VE YILDIZ SAYISI ILGILI URUNE EKLEME YAPALIM .... yapildi,
    //CART GORUNUMLU URUN LISTESI, gerek duyulmadi, tam uun isim listesi getirilecek


    // ==========ASAGIDAKI METHODLAR REACT UI ILE BIRLIKTE YAPILABILIR == SIMDI REACTA GECIYORUZ =======
    // ========= YAPILACAK ===
    // TAVSIYE EDILEN URUN LISTESI, ne tavsiyesi, indirim mi?
    // indirim olan urun listeleme =>user, ekleme, silme =>admin
    //TAVSIYE EDILENLERE URUN EKLEME
    // COK SATILANLARA URUN EKLEME
    // URUNLER VE SEPET TABLOLARINI RAM DE TUTMAYI DENEME
    //urunlere INDRIM, INDIRIM ORANI VE SATIS SAYISI EKLEDIK
    // SATIS SAYISINI URUN SATIS ONAYLANDIKTAN SONRA, (=HATTA TESLIM EDILDIKTEN SONRA=) URUN SATIS SAYISINA EKLENEBILIR,
    //SATIS SAYISINA GORE URUNLER CAGRILABILIR VEYA UI DA SATIS SAYISINA GORE SIRALANABILIR.

    // ====
}
